name: saturn

services:
  pg-database:
    image: postgres:14-alpine3.21
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pg-web:
    container_name: pg-web
    image: sosedoff/pgweb:latest
    environment:
      PGWEB_DATABASE_URL: postgres://postgres:postgres@pg-database:5432/postgres?sslmode=disable
    ports:
      - 8081:8081
    depends_on:
      pg-database:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "nc", "-vz", "127.0.0.1", "8081"]
      interval: 5s

  goose:
    build:
      context: ../..
      dockerfile: ./build/goose/Dockerfile
    environment:
      GOOSE_DRIVER: postgres
      GOOSE_DBSTRING: postgres://postgres:postgres@pg-database:5432/postgres?sslmode=disable
      GOOSE_MIGRATIONS_DIR: /migrations
    depends_on:
      pg-database:
        condition: service_healthy
    command: ["goose", "up"]

volumes:
  postgres-data:

networks:
  default:
    name: saturn
    external: true
